SET DEFINE OFF
INSERT INTO FREE (USERNAME) 
VALUES ('mondo_duplantis');
INSERT INTO FREE (USERNAME) 
VALUES ('athonyhopkins');
INSERT INTO FREE (USERNAME) 
VALUES ('paulpogba');
INSERT INTO FREE (USERNAME) 
VALUES ('zhouguanyu24');
