SET DEFINE OFF
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('0', 's1039', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('1', 's1039', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('2', 's1039', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('3', 's1039', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('4', 's1039', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('5', 's1039', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('0', 's1040', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('3', 's1040', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('2', 's1040', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('1', 's1040', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('4', 's1040', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('5', 's1040', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('3', 's1041', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('0', 's1041', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('4', 's1041', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('6', 's1041', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('3', 's1042', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('7', 's1042', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('8', 's1042', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('6', 's1042', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('3', 's1043', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('4', 's1043', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('6', 's1043', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('9', 's1044', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('10', 's1044', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('11', 's1044', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('12', 's1045', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('13', 's1045', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('14', 's1045', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('15', 's1046', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('16', 's1046', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('17', 's1046', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('15', 's1047', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('18', 's1047', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('17', 's1047', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('0', 's1048', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('19', 's1048', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('20', 's1048', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('0', 's1049', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('21', 's1049', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('22', 's1049', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('4', 's1049', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('0', 's1050', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('21', 's1050', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('22', 's1050', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('0', 's1051', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('1', 's1051', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('2', 's1051', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('3', 's1051', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('4', 's1051', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('5', 's1051', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('1', 's1052', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('23', 's1052', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('24', 's1052', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('25', 's1052', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('1', 's1053', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('23', 's1053', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('24', 's1053', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('25', 's1053', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('46', 's1035', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('47', 's1035', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('48', 's1035', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('49', 's1036', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('50', 's1036', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('51', 's1036', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('52', 's1038', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('53', 's1038', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('54', 's1038', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('0', 's492', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('1', 's492', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('2', 's492', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('3', 's492', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('4', 's492', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('22', 's492', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('55', 's610', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('56', 's610', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('57', 's610', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('1', 's686', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('24', 's686', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('58', 's686', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('26', 's1054001', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('26', 's1054002', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('26', 's1054003', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('26', 's1054004', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('26', 's1054005', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('26', 's1054006', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('26', 's1054007', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('26', 's1054008', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('26', 's1054009', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('26', 's1054010', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('26', 's1054011', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('26', 's1054012', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('26', 's1054013', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('26', 's1054014', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('26', 's1054015', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('26', 's1054016', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('26', 's1054017', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('26', 's1054018', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('26', 's1054019', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('26', 's1054020', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('27', 's1054001', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('27', 's1054002', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('27', 's1054003', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('27', 's1054004', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('27', 's1054005', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('27', 's1054006', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('27', 's1054007', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('27', 's1054008', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('27', 's1054009', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('27', 's1054010', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('27', 's1054011', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('27', 's1054012', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('27', 's1054013', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('27', 's1054014', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('27', 's1054015', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('27', 's1054016', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('27', 's1054017', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('27', 's1054018', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('27', 's1054019', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('27', 's1054020', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('28', 's1054001', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('28', 's1054002', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('28', 's1054003', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('28', 's1054004', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('28', 's1054005', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('28', 's1054006', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('28', 's1054007', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('28', 's1054008', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('28', 's1054009', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('28', 's1054010', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('28', 's1054011', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('28', 's1054012', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('28', 's1054013', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('28', 's1054014', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('28', 's1054015', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('28', 's1054016', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('28', 's1054017', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('28', 's1054018', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('28', 's1054019', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('28', 's1054020', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('29', 's1055001', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('29', 's1055002', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('29', 's1055003', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('29', 's1055004', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('29', 's1055005', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('29', 's1055006', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('29', 's1055007', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('29', 's1055008', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('29', 's1055009', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('29', 's1055010', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('30', 's1055001', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('30', 's1055002', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('30', 's1055003', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('30', 's1055004', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('30', 's1055005', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('30', 's1055006', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('30', 's1055007', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('30', 's1055008', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('30', 's1055009', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('30', 's1055010', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('31', 's1055001', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('31', 's1055002', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('31', 's1055003', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('31', 's1055004', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('31', 's1055005', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('31', 's1055006', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('31', 's1055007', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('31', 's1055008', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('31', 's1055009', 'acts');
INSERT INTO ACTS (CASTID, VIDEOID, ROLE) 
VALUES ('31', 's1055010', 'acts');
