SET DEFINE OFF
INSERT INTO MOVIE (VIDEOID, DATEOFRELEASE, RUNTIME, SEQUEL) 
VALUES ('s1039', to_date('2012/11/19', 'RRRR-MM-DD'), 143, 'Marvel Studios'' Avengers: Infinity War, Marvel Studios'' Avengers: Endgame');
INSERT INTO MOVIE (VIDEOID, DATEOFRELEASE, RUNTIME, SEQUEL) 
VALUES ('s1040', to_date('2012/11/19', 'RRRR-MM-DD'), 183, '');
INSERT INTO MOVIE (VIDEOID, DATEOFRELEASE, RUNTIME, SEQUEL) 
VALUES ('s1041', to_date('2012/11/19', 'RRRR-MM-DD'), 150, '');
INSERT INTO MOVIE (VIDEOID, DATEOFRELEASE, RUNTIME, SEQUEL) 
VALUES ('s1042', to_date('2012/11/19', 'RRRR-MM-DD'), 126, 'Marvel Studios'' Captain America: The Winter Soldier, Marvel Studios'' Captain America: Civil War');
INSERT INTO MOVIE (VIDEOID, DATEOFRELEASE, RUNTIME, SEQUEL) 
VALUES ('s1043', to_date('2012/11/19', 'RRRR-MM-DD'), 138, 'Marvel Studios'' Captain America: Civil War');
INSERT INTO MOVIE (VIDEOID, DATEOFRELEASE, RUNTIME, SEQUEL) 
VALUES ('s1044', to_date('2012/11/19', 'RRRR-MM-DD'), 126, '');
INSERT INTO MOVIE (VIDEOID, DATEOFRELEASE, RUNTIME, SEQUEL) 
VALUES ('s1045', to_date('2012/11/19', 'RRRR-MM-DD'), 116, '');
INSERT INTO MOVIE (VIDEOID, DATEOFRELEASE, RUNTIME, SEQUEL) 
VALUES ('s1046', to_date('2012/11/19', 'RRRR-MM-DD'), 122, 'Marvel Studios'' Guardians of the Galaxy Vol. 2');
INSERT INTO MOVIE (VIDEOID, DATEOFRELEASE, RUNTIME, SEQUEL) 
VALUES ('s1047', to_date('2012/11/19', 'RRRR-MM-DD'), 137, '');
INSERT INTO MOVIE (VIDEOID, DATEOFRELEASE, RUNTIME, SEQUEL) 
VALUES ('s1048', to_date('2012/11/19', 'RRRR-MM-DD'), 127, 'Marvel Studios'' Iron Man 2, Marvel Studios'' Iron Man 3');
INSERT INTO MOVIE (VIDEOID, DATEOFRELEASE, RUNTIME, SEQUEL) 
VALUES ('s1049', to_date('2012/11/19', 'RRRR-MM-DD'), 125, 'Marvel Studios'' Iron Man 3');
INSERT INTO MOVIE (VIDEOID, DATEOFRELEASE, RUNTIME, SEQUEL) 
VALUES ('s1050', to_date('2012/11/19', 'RRRR-MM-DD'), 132, '');
INSERT INTO MOVIE (VIDEOID, DATEOFRELEASE, RUNTIME, SEQUEL) 
VALUES ('s1051', to_date('2012/11/19', 'RRRR-MM-DD'), 145, 'Marvel Studios'' Avengers: Age of Ultron, Marvel Studios'' Avengers: Infinity War, Marvel Studios'' Avengers: Endgame');
INSERT INTO MOVIE (VIDEOID, DATEOFRELEASE, RUNTIME, SEQUEL) 
VALUES ('s1052', to_date('2012/11/19', 'RRRR-MM-DD'), 116, 'Marvel Studios'' Thor: The Dark World, Marvel Studios'' Thor: Ragnarok');
INSERT INTO MOVIE (VIDEOID, DATEOFRELEASE, RUNTIME, SEQUEL) 
VALUES ('s1053', to_date('2012/11/19', 'RRRR-MM-DD'), 114, 'Marvel Studios'' Thor: Ragnarok');
INSERT INTO MOVIE (VIDEOID, DATEOFRELEASE, RUNTIME, SEQUEL) 
VALUES ('s1035', to_date('2012/11/19', 'RRRR-MM-DD'), 80, '');
INSERT INTO MOVIE (VIDEOID, DATEOFRELEASE, RUNTIME, SEQUEL) 
VALUES ('s1036', to_date('2012/11/19', 'RRRR-MM-DD'), 43, 'Marvel Studios: Expanding the Universe');
INSERT INTO MOVIE (VIDEOID, DATEOFRELEASE, RUNTIME, SEQUEL) 
VALUES ('s1038', to_date('2012/11/19', 'RRRR-MM-DD'), 119, '');
INSERT INTO MOVIE (VIDEOID, DATEOFRELEASE, RUNTIME, SEQUEL) 
VALUES ('s492', to_date('2026/06/20', 'RRRR-MM-DD'), 152, 'Marvel Studios'' Avengers: Endgame');
INSERT INTO MOVIE (VIDEOID, DATEOFRELEASE, RUNTIME, SEQUEL) 
VALUES ('s610', to_date('2004/03/20', 'RRRR-MM-DD'), 137, '');
INSERT INTO MOVIE (VIDEOID, DATEOFRELEASE, RUNTIME, SEQUEL) 
VALUES ('s686', to_date('2005/12/19', 'RRRR-MM-DD'), 132, '');
