SET DEFINE OFF
INSERT INTO PREMIUM (USERNAME) 
VALUES ('paulnicklen');
INSERT INTO PREMIUM (USERNAME) 
VALUES ('jaychou');
INSERT INTO PREMIUM (USERNAME) 
VALUES ('andrewlloydwebber');
INSERT INTO PREMIUM (USERNAME) 
VALUES ('zhouguanyu');
