SET DEFINE OFF
INSERT INTO PLAYLIST (USERNAME, PLAYLISTNAME, VIDEOID) 
VALUES ('paulnicklen', 'marvel1', 's1039');
INSERT INTO PLAYLIST (USERNAME, PLAYLISTNAME, VIDEOID) 
VALUES ('paulnicklen', 'marvel2', 's1040');
INSERT INTO PLAYLIST (USERNAME, PLAYLISTNAME, VIDEOID) 
VALUES ('paulnicklen', 'marvel3', 's1041');
INSERT INTO PLAYLIST (USERNAME, PLAYLISTNAME, VIDEOID) 
VALUES ('jaychou', 'marvel1', 's1052');
INSERT INTO PLAYLIST (USERNAME, PLAYLISTNAME, VIDEOID) 
VALUES ('jaychou', 'marvel2', 's1043');
INSERT INTO PLAYLIST (USERNAME, PLAYLISTNAME, VIDEOID) 
VALUES ('andrewlloydwebber', 'marvel1', 's1042');
