SET DEFINE OFF
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('jaychou', 's1039', 143);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('jaychou', 's1040', 183);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('jaychou', 's1041', 150);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('jaychou', 's1042', 126);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('jaychou', 's1043', 138);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('jaychou', 's1044', 126);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('jaychou', 's1045', 116);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('jaychou', 's1046', 122);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('jaychou', 's1047', 137);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('jaychou', 's1048', 127);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('jaychou', 's1049', 125);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('jaychou', 's1050', 132);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('jaychou', 's1051', 145);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('jaychou', 's1052', 116);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('jaychou', 's1053', 114);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('jaychou', 's1035', 80);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('jaychou', 's1036', 43);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('jaychou', 's1038', 119);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('jaychou', 's492', 152);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('jaychou', 's610', 137);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('jaychou', 's686', 132);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('athonyhopkins', 's1039', 43);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('athonyhopkins', 's1040', 53);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('paulnicklen', 's1041', 150);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('paulnicklen', 's1042', 126);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('paulnicklen', 's1043', 138);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('paulnicklen', 's1052', 116);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('paulnicklen', 's1053', 114);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('andrewlloydwebber', 's1035', 80);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('mondo_duplantis', 's1050', 132);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('mondo_duplantis', 's1051', 145);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('mondo_duplantis', 's1052', 116);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('mondo_duplantis', 's1053', 114);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('mondo_duplantis', 's1035', 80);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('mondo_duplantis', 's1036', 43);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('mondo_duplantis', 's1038', 119);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('mondo_duplantis', 's492', 152);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('mondo_duplantis', 's610', 137);
INSERT INTO WATCHES (USERNAME, VIDEOID, TIMESTAMPS) 
VALUES ('mondo_duplantis', 's686', 132);
